MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  CLS_AGNOSTIC_BBOX_REG: True
  BACKBONE:
    FREEZE_CONV_BODY_AT: 4
  RPN:
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
    PRE_NMS_TOP_N_TRAIN: 12000
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 600
    FPN_POST_NMS_PER_BATCH: False      # Do NMS per image rather than per batch
  ROI_HEADS:
    SCORE_THRESH: 0.05
  ROI_BOX_HEAD:
    NUM_CLASSES: 32
INPUT:
  MIN_SIZE_TRAIN: (324,)
  MAX_SIZE_TRAIN: 576
  MIN_SIZE_TEST: 324
  MAX_SIZE_TEST: 576
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
DATASETS:
  TRAIN: ("active_vision_coco_set_1_train",)
  TEST: ("active_vision_coco_set_1_test",)
SOLVER:
  # Batch size = 1
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (27306, 45510)
  CHECKPOINT_PERIOD: 9102
  MAX_ITER: 54612    # NUM_EPOCHS * DATASET_SIZE/BATCH_SIZE = 6 * 9102 / 1
  IMS_PER_BATCH: 1 
TEST:
  IMS_PER_BATCH: 1
