MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  CLS_AGNOSTIC_BBOX_REG: True
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 2000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.05
  ROI_BOX_HEAD:
    NUM_CLASSES: 32
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
INPUT:
  MIN_SIZE_TRAIN: (324,)
  MAX_SIZE_TRAIN: 576
  MIN_SIZE_TEST: 324
  MAX_SIZE_TEST: 576
  PIXEL_MEAN: [102.9801, 115.9465, 122.7717]
DATASETS:
  TRAIN: ("active_vision_coco_set_1_train",)
  TEST: ("active_vision_coco_set_1_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # Batch size = 1
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (27306, 45510)
  CHECKPOINT_PERIOD: 9102
  MAX_ITER: 54612    # NUM_EPOCHS * DATASET_SIZE/BATCH_SIZE = 6 * 9102 / 1
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1
