MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 600
    ANCHOR_SIZES: (32, 64, 128, 256, 512)
  ROI_HEADS:
    SCORE_THRESH: 0.60
  ROI_BOX_HEAD:
    NUM_CLASSES: 32
DATASETS:
  TRAIN: ("active_vision_coco_set_1_train",)
  TEST: ("active_vision_coco_set_1_test",)
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  STEPS: (27306, 45510)
  CHECKPOINT_PERIOD: 1000
  MAX_ITER: 54612    # NUM_EPOCHS * DATASET_SIZE/BATCH_SIZE = 6 * 9102 / 1
  IMS_PER_BATCH: 1
TEST:
  IMS_PER_BATCH: 1
